# Generated by Django 6.0.4 on 2026-04-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Employee'), (2, 'Manager'), (3, 'Admin')], default=1),
        ),
    ]
