# Generated by Django 6.0.4 on 2026-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Casual'), (2, 'Sick')], default=1),
        ),
    ]
