# Generated by Django 6.0.4 on 2026-04-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='manager_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
